name: 'Process DBT Test Results'
description: 'Processes and formats DBT test results from output log'

inputs:
  log-file:
    description: 'Path to the DBT output log file'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [ ! -f "${{ inputs.log-file }}" ]; then
          echo "No test output file found"
          exit 0
        fi

        # Get number of errors from the "Done." line
        num_failed_tests=$(grep "Done." "${{ inputs.log-file }}" | grep -o "ERROR=[0-9]*" | cut -d'=' -f2)

        if [ -z "$num_failed_tests" ] || [ "$num_failed_tests" -eq 0 ]; then
          echo "No failed tests found"
          exit 0
        fi

        echo "🔴 Found $num_failed_tests failed tests"
        echo "----------------------------------------"

        while IFS= read -r line; do
          if [[ $line == *"compiled code at"* ]]; then
            sql_file=$(echo "$line" | awk '{print $NF}')
            test_name=$(basename "$sql_file" .sql)

            echo "📄 SQL for failed test: $test_name"
            echo "```sql"
            if [ -f "$sql_file" ]; then
              cat "$sql_file"
            else
              echo "SQL file not found: $sql_file"
            fi
            echo "```"
            echo "----------------------------------------"
          fi
        done < "${{ inputs.log-file }}"
