name: 'Process DBT Test Results'
description: 'Processes and formats DBT test results from output log'

inputs:
  project-folder:
    description: 'Path to the DBT project folder'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: ${{ inputs.project-folder }}
      run: |
        echo "Content of unique_some_model_number.sql:"
        echo "----------------------------------------"
        cat target/run/starlight/models/example/schema.yml/unique_some_model_number.sql
        echo "----------------------------------------"
