name: 'Process DBT Test Results'
description: 'Processes and formats DBT test results from output log'

inputs:
  project-folder:
    description: 'Path to the DBT project folder'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: ${{ inputs.project-folder }}
      run: |
        echo "Current directory: $(pwd)"
        
        echo "Looking for these files:"
        echo "1. $(pwd)/target/compiled/starlight/models/example/schema.yml/unique_my_second_dbt_model_id.sql"
        echo "2. $(pwd)/target/compiled/starlight/models/example/schema.yml/unique_some_model_number.sql"
        
        echo -e "\nVerifying path components:"
        echo "Target dir exists: $(test -d "target" && echo "YES" || echo "NO")"
        echo "Compiled dir exists: $(test -d "target/compiled" && echo "YES" || echo "NO")"
        echo "Starlight dir exists: $(test -d "target/compiled/starlight" && echo "YES" || echo "NO")"
        echo "Models dir exists: $(test -d "target/compiled/starlight/models" && echo "YES" || echo "NO")"
        echo "Example dir exists: $(test -d "target/compiled/starlight/models/example" && echo "YES" || echo "NO")"
        echo "Schema.yml dir exists: $(test -d "target/compiled/starlight/models/example/schema.yml" && echo "YES" || echo "NO")"
        
        echo -e "\nListing all SQL files in target:"
        find target -name "*.sql"

        if [ ! -f "dbt_output.log" ]; then
          echo "No test output file found"
          exit 0
        fi

        # Get number of errors from the "Done." line
        num_failed_tests=$(grep "Done." "dbt_output.log" | grep -o "ERROR=[0-9]*" | cut -d'=' -f2)

        if [ -z "$num_failed_tests" ] || [ "$num_failed_tests" -eq 0 ]; then
          echo "No failed tests found"
          exit 0
        fi

        echo "🔴 Found $num_failed_tests failed tests"
        echo "----------------------------------------"

        while IFS= read -r line; do
          if [[ $line == *"compiled code at"* ]]; then
            # Extract SQL file path
            sql_file=$(echo "$line" | awk '{print $5}')
            test_name=$(basename "$sql_file" .sql)
            echo "Found test failure for: $test_name"
            echo "Looking for SQL file at: $sql_file"
            
            echo "📄 SQL for failed test: $test_name"
            if [ -f "$sql_file" ]; then
              echo "```sql"
              cat "$sql_file"
              echo "```"
            else
              echo "File not found at expected location: $sql_file"
              echo "Searching for file..."
              found_file=$(find target -name "$(basename "$sql_file")")
              if [ -n "$found_file" ]; then
                echo "Found at: $found_file"
                echo "```sql"
                cat "$found_file"
                echo "```"
              else
                echo "Could not find SQL file anywhere in target directory"
              fi
            fi
            echo "----------------------------------------"
          fi
        done < "dbt_output.log"
