name: 'Process DBT Test Results'
description: 'Processes and formats DBT test results from output log'

inputs:
  project-folder:
    description: 'Path to the DBT project folder'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: ${{ inputs.project-folder }}
      run: |
        echo "=== DBT Output Log Content ==="
        if [ -f "dbt_output.log" ]; then
          cat dbt_output.log
        else
          echo "Log file not found at: $(pwd)/dbt_output.log"
          ls -la
        fi
        echo "=== End of Log Content ==="
