starlight:
  target: development
  outputs:
    development:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      role: developer
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      authenticator: username_password_mfa
      database: starlight
      warehouse: developer
      schema: "dbt_{{ env_var('SNOWFLAKE_USER') }}"
      threads: 16
      client_session_keep_alive: false
    production:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      role: github
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      authenticator: username_password_mfa
      database: starlight
      warehouse: github
      schema: datawarehouse
      threads: 16
      client_session_keep_alive: false
    github:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: github
      role: github
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"
      database: "{{ env_var('DATABASE') }}"
      warehouse: github
      schema: datawarehouse
      threads: 16
      client_session_keep_alive: false

