name: 'dbt Action'
description: 'Runs dbt commands with Snowflake'

inputs:
  commands:
    required: true
    description: 'The commands that should run. E.g., `dbt deps`, `dbt run`, `dbt build`.'
  database:
    required: false
    description: 'The analytical database.'
    default: 'starlight'
  schema:
    required: false
    description: 'The production schema.'
    default: 'datawarehouse'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: ./.github/actions/setup-python

    - name: Install dbt-core
      uses: ./.github/actions/install-python-dependency
      with:
        dependency: dbt-core

    - name: Install dbt-snowflake
      uses: ./.github/actions/install-python-dependency
      with:
        dependency: dbt-snowflake

    - name: Copy profiles.yml
      shell: bash
      run: |
        sudo cp -r .dbt/ /home/runner/

    - name: Execute provided script
      shell: bash
      env:
        SNOWFLAKE_ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
        SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
        DATABASE: ${{ inputs.database }}
      run: |
        ${{ inputs.commands }}
