name: Install Python Dependencies

runs:
  using: composite
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        for dep in "${{ inputs.dependencies }}"; do
          grep "$dep" requirements.txt | xargs -n 1 pip install
          pip list | grep "$dep"
        done

inputs:
  dependency:
    description: "The dependencies to install (comma-separated)"
    required: true
    type: string
