name: Setup Python

runs:
  using: composite

  steps:
      - name: Python version from .python-version
        run: echo "python_version=$(cat .python-version)" >>  "$GITHUB_ENV"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}
