name: Setup Python

runs:
  using: composite

  steps:
    - name: Python version from .python-version
      shell: bash
      run: |
        echo "python_version=$(cat .python-version)" >>  "$GITHUB_ENV"
        echo "Python version: ${{ env.python_version }}"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python_version }}
