name: DBT on PR close

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * *'

concurrency: production

jobs:
  dbt:
    name: DBT
    uses: ./.github/workflows/dbt.yml
    secrets:
      SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
    with:
      commands: |
        dbt deps
        dbt build --target github
