name: DBT Manual Dispatch

on:
  workflow_dispatch:

concurrency: production

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  dbt:
    name: DBT
    uses: ./.github/workflows/dbt.yml
    secrets:
      SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
    with:
      with-dbt-docs: true
      commands: |
        dbt deps
        dbt debug --target github
        dbt build --target github
