name: dbt on PR

on:
  push:
    branches:
      - '*'

jobs:
  dbt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - uses: ./.github/workflows/dbt.yml
        with:
          commands: |
            cd starlight
            env
            dbt debug --target github
            dbt deps --target github
            echo 1