name: DBT on PR

on:
  push:
    branches:
      - '*'

jobs:
  dbt:
    name: DBT
    uses: ./.github/workflows/dbt.yml
    secrets:
      SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
    with:
      with-initial-manifest: true
      schema: "pr-${{ github.ref_name }}"
      commands: |
        dbt debug --target github
        dbt deps
        dbt seed --target github
        dbt run --target github
        dbt test --target github
