name: Call Reusable Workflow

on:
  push:
    branches:
      - '**'

jobs:
  use-reusable:
    uses: ./.github/workflows/dbt/dbt.yml
    with:
      commands: |
        echo "Line 1"
        echo "Line 2"
        echo "Line 3"
