name: DBT on PR close

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - starlight/**

jobs:
  dbt:
    name: DBT
    uses: ./.github/workflows/dbt.yml
    secrets:
      SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
    with:
      commands: |
        dbt run-operation drop_schema --args '{schema_name: something}' --target github
