name: DBT Manual Run

on:
  workflow_dispatch:

concurrency: production

jobs:
  dbt:
    name: DBT
    uses: ./.github/workflows/dbt.yml
    secrets:
      SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
    with:
      commands: |
        dbt debug --target github
        dbt deps
        dbt seed --target github
        dbt run --target github
        dbt test --target github
