name: DBT on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency: pr-${{ github.event.pull_request.number }}

jobs:
  dbt:
    name: DBT
    uses: ./.github/workflows/dbt.yml
    secrets:
      SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
    with:
      with-initial-manifest: true
      schema: "pr_${{ github.event.pull_request.number }}"
      commands: |
        dbt debug --target github
        dbt deps
        dbt seed --target github
        dbt run --target github
        dbt test --target github
