name: DBT on PR close

on:
  pull_request:
    types:
      - closed
    paths:
      - starlight/**

concurrency: production

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  dbt:
    name: DBT
    uses: ./.github/workflows/dbt.yml
    secrets:
      SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
    with:
      with-dbt-docs: true
      commands: |
        dbt deps
        dbt build --target github
        dbt run-operation run_query --args '{"sql": "drop schema if exists pr_${{ github.event.pull_request.number }};"}' --target github
