name: Call Reusable Workflow

on:
  push:
    branches:
      - '*'

jobs:
  execute-dbt-commands:
    uses: ./.github/workflows/dbt.yml
    with:
      commands: |
        cd starlight
        dbt debug
        dbt deps
