name: Reusable Workflow

on:
  workflow_call:
    inputs:
      commands:
        required: true
        description: The commands that should run. E.g., `dbt deps`, `dbt run`, `dbt build`.
        type: string
      database:
        required: false
        description: The analytical database.
        default: starlight
        type: string
      schema:
        required: false
        description: The production schema.
        default: datawarehouse
        type: string
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: ./.github/actions/setup-python

      - name: Install dbt-core
        uses: ./.github/actions/install-python-dependency
        with:
          dependency: dbt-core

      - name: Install dbt-snowflake
        uses: ./.github/actions/install-python-dependency
        with:
          dependency: dbt-core

      - name: Execute provided script
        run: |
          ${{ inputs.commands }}
