name: YAMLLint

on:
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install yamllint from requirements.txt
        run: |
          python -m pip install --upgrade pip
          grep yamllint requirements.txt | xargs -n 1 pip install

      - name: Lint YAML files
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git ls-files --exclude-standard --cached --others -- '*.yaml' '*.yml' | xargs yamllint
